### PR TITLE
Update .gitattributes and remove bower.json + .htaccess

### PR DESCRIPTION
**Pull request by williamdes**

### CODE REVIEW

**Comment by williamdes** [comment]
Should I delete the file too?
The htaccess does nothing, delete also?

**Comment by williamdes** [comment]
Last question: should the composer.json names pace be updated?
Or only the homepage field?

**Comment by bsweeney** [comment]
I think you're fine to delete those files. I was trying to decide the best time to update the namespace. I'm about ready to release a new version of Dompdf so I guess now would be a good time for it?

**Comment by williamdes** [comment]
Yes definitely, I will not be on my workstation until this evening
Feel free to do the changes in the mean time and close this one
Can you give me some time to have a last check on my side that everything is ready for Debian too?
Maybe I have one more change to do, not very sure about it

**Comment by williamdes** [comment]
I think I am all done here

I removed one config param that is not used in phpunit since a long time (Author says: https://stackoverflow.com/a/44331140/5155484)

**Comment by williamdes** [comment]
Why does composer say this lib is LGPL 3.0 and the LICENSE file says it is 2.1 ?

**Review by bsweeney — APPROVED** [review]

**Pull request merged**
